- name: Deploy grafana
  community.docker.docker_container:
    name: grafana
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
    restart_policy: always
