- name: Creates directory
  file:
    path: /etc/prometheus
    state: directory
- name: copy prometheus config
  copy:
    src: templates/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
- name: deploy prometheus
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus
    volumes:
      - /etc/prometheus:/etc/prometheus
      - /var/lib/prometheus:/var/lib/prometheus
    ports:
      - "9090:9090"
    restart_policy: always
