- name: add docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
- name: update docker sources.list
  copy:
    src: templates/docker.list
    dest: /etc/apt/sources.list.d/docker.list
- name: install docker
  apt:
    pkg:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - python3-docker
    state: latest
    update_cache: true
- name: Make sure remote lab user is in docker group
  user:
    name: "lab"
    group: "docker"
- name: set insecure registries
  copy:
    src: templates/daemon.json
    dest: /etc/docker/daemon.json
- name: make sure a service unit is running
  systemd:
    name: docker
    state: restarted
    enabled: true
- name: make sure watchtower is running
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower
    env:
      WATCHTOWER_POLL_INTERVAL: "120"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: always
- name: create cronjob
  ansible.builtin.cron:
    name: "clean docker images"
    minute: "0"
    hour: "4"
    job: "/usr/bin/docker system prune -f > ~/prune.out"
