- name: update all hosts
  hosts: server
  become: true
  become_method: su
  tasks:
    - name: ensure that the system is up to date
      apt:
        autoremove: yes
        clean: yes
        update_cache: yes
        name: "*"
        state: latest
