name: Deployment

on:
  push:
    branches: [bloat]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: ./.github/actions/ansible
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}